dTect V7.0.3rc3
Parameters
2023-09-27T10:05:48Z
!
Attributes.0.DataType: Other
Attributes.0.Definition: Storage id=100010.2 output=0
Attributes.0.Hidden: No
Attributes.0.Index: 26
Attributes.0.UserRef: Velocity model 4 layers - no SRD
Attributes.1.DataType: Other
Attributes.1.Definition: Horizon horid=100020.2 type=Z relz=Yes output=0
Attributes.1.Hidden: No
Attributes.1.Index: 11
Attributes.1.Input.0: 0
Attributes.1.UserRef: Zrel FS8
Attributes.10.DataType: Other
Attributes.10.Definition: Math expression="relFS4 < DZ+1e-7 ? undef : c0" constant0=2400  output=0
Attributes.10.Hidden: No
Attributes.10.Index: 8
Attributes.10.Input.0: 3
Attributes.10.UserRef: Velocity below FS4
Attributes.11.DataType: Other
Attributes.11.Definition: Math expression=sum(x0,x1,x2,x3,x4,x5,x6) output=0
Attributes.11.Hidden: No
Attributes.11.Index: 1
Attributes.11.Input.0: 7
Attributes.11.Input.1: 4
Attributes.11.Input.2: 8
Attributes.11.Input.3: 5
Attributes.11.Input.4: 9
Attributes.11.Input.5: 6
Attributes.11.Input.6: 10
Attributes.11.UserRef: Velocity model
Attributes.12.DataType: Other
Attributes.12.Definition: Math expression="velocitymodel / c0" constant0=0.3048  output=0
Attributes.12.Hidden: No
Attributes.12.Index: 0
Attributes.12.Input.0: 11
Attributes.12.UserRef: Velocity model ft/s
Attributes.2.DataType: Other
Attributes.2.Definition: Horizon horid=100020.4 type=Z relz=Yes output=0
Attributes.2.Hidden: No
Attributes.2.Index: 14
Attributes.2.Input.0: 0
Attributes.2.UserRef: Zrel FS7
Attributes.3.DataType: Other
Attributes.3.Definition: Horizon horid=100020.6 type=Z relz=Yes output=0
Attributes.3.Hidden: No
Attributes.3.Index: 17
Attributes.3.Input.0: 0
Attributes.3.UserRef: Zrel FS4
Attributes.4.DataType: Other
Attributes.4.Definition: Math expression="relFS8 > 1e-7 && relFS8 < DZ+1e-7 ? (1 / ( ( 1 - (relFS8/DZ) ) / c0 + ( relFS8 / DZ) / c1)) : undef" constant0=1960 constant1=2175  output=0
Attributes.4.Hidden: No
Attributes.4.Index: 3
Attributes.4.Input.0: 1
Attributes.4.UserRef: Velocity around FS8
Attributes.5.DataType: Other
Attributes.5.Definition: Math expression="relFS7 > 1e-7 && relFS7 < DZ+1e-7 ? (1 / ( ( 1 - (relFS7/DZ) ) / c0 + ( relFS7 / DZ) / c1)) : undef" constant0=2175 constant1=2260  output=0
Attributes.5.Hidden: No
Attributes.5.Index: 5
Attributes.5.Input.0: 2
Attributes.5.UserRef: Velocity around FS7
Attributes.6.DataType: Other
Attributes.6.Definition: Math expression="relFS4 > 1e-7 && relFS4 < DZ+1e-7 ? (1 / ( ( 1 - (relFS4/DZ) ) / c0 + ( relFS4 / DZ) / c1)) : undef" constant0=2260 constant1=2400  output=0
Attributes.6.Hidden: No
Attributes.6.Index: 7
Attributes.6.Input.0: 3
Attributes.6.UserRef: Velocity around FS4
Attributes.7.DataType: Other
Attributes.7.Definition: Math expression="Z < 37.5 ? c0 : (Z < 42.5 ? 1/((1/c0+1/c1)/2) : relFS8 < 1e-7 ? c1 : undef)" constant0=1500 constant1=1960  output=0
Attributes.7.Hidden: No
Attributes.7.Index: 2
Attributes.7.Input.0: 1
Attributes.7.UserRef: Velocity above FS8
Attributes.8.DataType: Other
Attributes.8.Definition: Math expression="relFS8 < DZ+1e-7 ? undef : (relFS7 < 1e-7 ? c0 : undef)" constant0=2175  output=0
Attributes.8.Hidden: No
Attributes.8.Index: 4
Attributes.8.Input.0: 1
Attributes.8.Input.1: 2
Attributes.8.UserRef: Velocity between FS8 and FS7
Attributes.9.DataType: Other
Attributes.9.Definition: Math expression="relFS7 < DZ+1e-7 ? undef : (relFS4 < 1e-7 ? c0 : undef)" constant0=2260  output=0
Attributes.9.Hidden: No
Attributes.9.Index: 6
Attributes.9.Input.0: 2
Attributes.9.Input.1: 3
Attributes.9.UserRef: Velocity between FS7 and FS4
Attributes.MaxNrKeys: 12
Attributes.Type: 3D
Data Root: /auto/d26/surveys
ExecPars.Monitor: Yes`
ExecPars.PriorityLevel: -1
ExecPars.ProgramType: Batch`
Log file: /auto/d26/surveys/F3_Demo_2020_Depth-m/Proc/Velocity_model__INT__depth-m__ft_s__log.txt
Output.0.Attributes.0: 12
Output.0.Attributes.MaxNrKeys: 1
Output.0.Extend Traces To Survey Z Range: No
Output.0.Seismic.ID: 100010.11
Output.Subsel.Estimated MBs: 0
Output.Subsel.First Cross-line: 700
Output.Subsel.First In-line: 426
Output.Subsel.GeomID: -1
Output.Subsel.Last Cross-line: 1200
Output.Subsel.Last In-line: 426
Output.Subsel.Step Cross-line: 2
Output.Subsel.Step In-line: 1
Output.Subsel.Survey ID: -1
Output.Subsel.Type: Range
Output.Subsel.Z range: 400`1200`5
Output.Type: Cube
Program.Args: 
Program.Name: od_process_attrib
Survey: F3_Demo_2020_Depth-m
Target: Velocity model (INT) depth-m (ft/s)
!
