dTect V6.6
Parameters
Wed 27 Sep 2023, 08:45:55
!
Output.Type: Cube
Attributes.15.Definition: Math expression=sum(x0,x1,x2,x3,x4,x5,x6) output=0
Attributes.15.UserRef: Velocity model
Attributes.15.Hidden: No
Attributes.15.DataType: Other
Attributes.15.Index: 0
Attributes.15.Input.0: 4
Attributes.15.Input.1: 11
Attributes.15.Input.2: 5
Attributes.15.Input.3: 12
Attributes.15.Input.4: 6
Attributes.15.Input.5: 13
Attributes.15.Input.6: 7
Attributes.4.Definition: Math expression="Z < 0.05 ? c0 : (Z < 0.054 ? ((c0+c1)/2) : relFS8 < 1e-7 ? c1 : undef)" constant0=1500 constant1=1960  output=0
Attributes.4.UserRef: Velocity above FS8
Attributes.4.Hidden: No
Attributes.4.DataType: Other
Attributes.4.Index: 1
Attributes.4.Input.0: 1
Attributes.11.Definition: Math expression="relFS8 > 1e-8 && relFS8 < DZ+1e-8 ? c0 * ( 1 - (relFS8/DZ) ) + c1 * ( relFS8 / DZ) : undef" constant0=1960 constant1=2175  output=0
Attributes.11.UserRef: Velocity around FS8
Attributes.11.Hidden: No
Attributes.11.DataType: Other
Attributes.11.Index: 2
Attributes.11.Input.0: 1
Attributes.5.Definition: Math expression="relFS8 < DZ+1e-8 ? undef : (relFS7 < 1e-8 ? c0 : undef)" constant0=2175  output=0
Attributes.5.UserRef: Velocity between FS8 and FS7
Attributes.5.Hidden: No
Attributes.5.DataType: Other
Attributes.5.Index: 3
Attributes.5.Input.0: 1
Attributes.5.Input.1: 2
Attributes.12.Definition: Math expression="relFS7 > 1e-8 && relFS7 < DZ+1e-8 ? c0 * ( 1 - (relFS7/DZ) ) + c1 * ( relFS7 / DZ) : undef" constant0=2175 constant1=2260  output=0
Attributes.12.UserRef: Velocity around FS7
Attributes.12.Hidden: No
Attributes.12.DataType: Other
Attributes.12.Index: 4
Attributes.12.Input.0: 2
Attributes.6.Definition: Math expression="relFS7 < DZ+1e-8 ? undef : (relFS4 < 1e-8 ? c0 : undef)" constant0=2260  output=0
Attributes.6.UserRef: Velocity between FS7 and FS4
Attributes.6.Hidden: No
Attributes.6.DataType: Other
Attributes.6.Index: 5
Attributes.6.Input.0: 2
Attributes.6.Input.1: 3
Attributes.13.Definition: Math expression="relFS4 > 1e-8 && relFS4 < DZ+1e-8 ? c0 * ( 1 - (relFS4/DZ) ) + c1 * ( relFS4 / DZ) : undef" constant0=2260 constant1=2400  output=0
Attributes.13.UserRef: Velocity around FS4
Attributes.13.Hidden: No
Attributes.13.DataType: Other
Attributes.13.Index: 6
Attributes.13.Input.0: 3
Attributes.7.Definition: Math expression="relFS4 < DZ+1e-8 ? undef : c0" constant0=2400  output=0
Attributes.7.UserRef: Velocity below FS4
Attributes.7.Hidden: No
Attributes.7.DataType: Other
Attributes.7.Index: 7
Attributes.7.Input.0: 3
Attributes.1.Definition: Horizon horid=100020.3 type=Z relz=Yes output=0
Attributes.1.UserRef: TWT rel FS8
Attributes.1.Hidden: No
Attributes.1.DataType: Other
Attributes.1.Index: 10
Attributes.1.Input.0: 0
Attributes.2.Definition: Horizon horid=100020.4 type=Z relz=Yes output=0
Attributes.2.UserRef: TWT rel FS7
Attributes.2.Hidden: No
Attributes.2.DataType: Other
Attributes.2.Index: 13
Attributes.2.Input.0: 0
Attributes.3.Definition: Horizon horid=100020.9 type=Z relz=Yes output=0
Attributes.3.UserRef: TWT rel FS4
Attributes.3.Hidden: No
Attributes.3.DataType: Other
Attributes.3.Index: 16
Attributes.3.Input.0: 0
Attributes.0.Definition: Storage id=100010.2 output=0
Attributes.0.UserRef: Seismic
Attributes.0.Hidden: No
Attributes.0.DataType: Other
Attributes.0.Index: 25
Attributes.MaxNrKeys: 15
Attributes.Type: 3D
Output.0.Attributes.MaxNrKeys: 1
Output.0.Attributes.0: 15
Output.0.Seismic.ID: 100010.8
Output.0.Extend Traces To Survey Z Range: No
Output.Subsel.Type: Range
Output.Subsel.First In-line: 426
Output.Subsel.First Cross-line: 700
Output.Subsel.Last In-line: 426
Output.Subsel.Last Cross-line: 1200
Output.Subsel.Step In-line: 1
Output.Subsel.Step Cross-line: 2
Output.Subsel.Survey ID: -1
Output.Subsel.Z range: 0.4`1.1`0.004
Output.Subsel.Estimated MBs: 0
Target: Velocity_model_INT_INL426 in Time (m/s)
Log file: /auto/d26/surveys/testsurveys/ODData/F3_Test_Survey/Proc/Velocity_model_INT_INL426_log.txt
Program.Name: od_process_attrib
Program.Args: 
ExecPars.Monitor: Yes`
ExecPars.ProgramType: Batch`
ExecPars.PriorityLevel: -1
Survey: F3_Test_Survey
Data Root: /auto/d26/surveys/testsurveys/ODData
!
