dTect V7.0.3rc3
Parameters
2023-09-28T14:52:26Z
!
Attributes.1.DataType: Other
Attributes.1.Definition: Storage id=100010.113 output=0
Attributes.1.Hidden: No
Attributes.1.Index: 1
Attributes.1.UserRef: Velocity model (RMS) time-s (m/s)
Attributes.2.DataType: Other
Attributes.2.Definition: Math expression="vel / c0" constant0=0.3048  output=0
Attributes.2.Hidden: No
Attributes.2.Index: 0
Attributes.2.Input.0: 1
Attributes.2.UserRef: Velocity model (RMS) time-s (ft/s)
Attributes.MaxNrKeys: 2
Attributes.Type: 3D
Data Root: C:\Surveys\testsurveys\ODData
ExecPars.Monitor: Yes`
ExecPars.PriorityLevel: -1
ExecPars.ProgramType: Batch`
Log file: C:\Surveys\testsurveys\ODData\F3_Test_Survey\Proc\Velocity_model__RMS__time-s__ft_s__log.txt
Output.0.Attributes.0: 2
Output.0.Attributes.MaxNrKeys: 1
Output.0.Extend Traces To Survey Z Range: No
Output.0.Seismic.ID: 100010.114
Output.Subsel.Estimated MBs: 0
Output.Subsel.First Cross-line: 700
Output.Subsel.First In-line: 426
Output.Subsel.GeomID: -1
Output.Subsel.Last Cross-line: 1200
Output.Subsel.Last In-line: 426
Output.Subsel.Random: No
Output.Subsel.Step Cross-line: 2
Output.Subsel.Step In-line: 2
Output.Subsel.Survey ID: -1
Output.Subsel.Type: Range
Output.Subsel.Z range: 0.4`1.1`0.004
Output.Type: Cube
Program.Args: 
Program.Name: od_process_attrib
Survey: F3_Test_Survey
Target: Velocity model (RMS) time-s (ft/s)
!
